/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as StylePreviewRouteImport } from './routes/style-preview'
import { Route as GroupGroupIdRouteImport } from './routes/group.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const StylePreviewRoute = StylePreviewRouteImport.update({
  id: '/style-preview',
  path: '/style-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupGroupIdRoute = GroupGroupIdRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/style-preview': typeof StylePreviewRoute
  '/group/$groupId': typeof GroupGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/style-preview': typeof StylePreviewRoute
  '/group/$groupId': typeof GroupGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/style-preview': typeof StylePreviewRoute
  '/group/$groupId': typeof GroupGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/friends' | '/style-preview' | '/group/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/friends' | '/style-preview' | '/group/$groupId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/friends'
    | '/style-preview'
    | '/group/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FriendsRoute: typeof FriendsRoute
  StylePreviewRoute: typeof StylePreviewRoute
  GroupGroupIdRoute: typeof GroupGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-preview': {
      id: '/style-preview'
      path: '/style-preview'
      fullPath: '/style-preview'
      preLoaderRoute: typeof StylePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$groupId': {
      id: '/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof GroupGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FriendsRoute: FriendsRoute,
  StylePreviewRoute: StylePreviewRoute,
  GroupGroupIdRoute: GroupGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
